topology:
  zones:
    field:
      subnet: 10.0.1.0/24
      hosts:
        - name: h1
          role: field
        - name: h2
          role: field
        - name: h3
          role: rtu
        - name: h4
          role: rtu

    control:
      subnet: 10.0.2.0/24
      hosts:
        - name: h5
          role: gateway

    it:
      subnet: 10.0.3.0/24
      hosts:
        - name: h6
          role: pandapower
        - name: h7
          role: attacker

  links:
    - [h1, h3]
    - [h2, h3]
    - [h3, h5]
    - [h5, h6]
    - [h6, h7]

network:
  bandwidth: 5
